### PR TITLE
add JumpProblems to library

### PR DESCRIPTION
**Pull request by isaacsas**
Adds four `JumpProblem`s to the library.

### CODE REVIEW

**Comment by isaacsas** [comment]
Happy to, but I don't think I have merge permissions here.

**Comment by ChrisRackauckas** [comment]
Added.

**Comment by isaacsas** [comment]
Awesome, will do then!

**Comment by isaacsas** [comment]
Hmm, still not seeing a merge button. I'll check back later in case this is just a delay on Github propagating the permissions change.

**Comment by ChrisRackauckas** [comment]
I accidentally didn't give it write privs. Should be good now.

**Comment by isaacsas** [comment]
Sounds good.

**Pull request merged**
